- name: user module demo
  hosts: all
  become: true
  vars:
    user: "root"
    password: "rnjddtltngfhjkmnjnutq)0))"
  tasks:
    - name: change password
      ansible.builtin.user:
        name: "{{ user }}"
        state: present
        password: "{{ password | password_hash('sha512') }}"
