- name: dns configure NORD dc
  hosts: all
  become: no
  user: root
 
  tasks:
    - name: Copy file with owner and permissions
      ansible.builtin.copy:
        src: /mnt/ansible-playbooks/nord/resolv.conf
        dest: /etc/resolv.conf
        owner: root
        group: root
        mode: '0644' 
