- name: cleaner
  hosts: all
  tasks:
    - name: clear old docker images
      remote_user: admin
      shell: yes | docker system prune -a --volumes 
      register: cri_clear
    - debug:
        msg: ""
