- name: create, find and delete old backups
  hosts: etcd
  tasks:        
    - name: Run etcd backup
      shell: "etcdctl --endpoints={{ endpoints }} --cacert={{ cacert }} --key={{ key }} snapshot save {{ etcd_backup_dir }}-{{ ansible_date_time.year }}-{{ ansible_date_time.month }}-{{ ansible_date_time.day }.db"
      become: yes
      
    - name: Find old backup files
      find:
        paths: "{{ etcd_backup_dir }}"
        patterns: "*.db" 
        age: 3d
        recurse: yes
      register: old_backups

    - name: Delete old backup files
      file:
        path: "{{ item.path }}"
        state: absent
      with_items: "{{ old_backups.files }}"
