- name: Find and delete old backups
  hosts: etcd
  tasks:
    - name: Set variables
      set_fact:
       cur_date: "{{ tstamp.stdout[0:10]}}"
       
    - name: Run etcd backup
      shell: "etcdctl --endpoints={{ endpoints }} --cacert=/{{ cacert }} --key=/{{ key }} snapshot save {{ etcd_backup_dir }}-{{ cur_date }}.db"
      become: yes
      
    - name: Find old backup files
      find:
        paths: {{ etcd_backup_dir }}
        patterns: "*.db" 
        age: 3d
        recurse: yes
      register: old_backups

    - name: Delete old backup files
      file:
        path: "{{ item.path }}"
        state: absent
      with_items: "{{ old_backups.files }}"
