- name: journald configure
  hosts: all
  become: no
  user: root
 
  tasks:
    - name: Copy file with owner and permissions
      ansible.builtin.copy:
        src: /mnt/ansible-playbooks/journald/journald.conf
        dest: /etc/systemd/journald.conf
        owner: root
        group: root
        mode: '0644'   
 
    - name: Restart journald
      ansible.builtin.service:
        name: systemd-journald.service
        state: restarted
        
