- name: find and delete trace.log
  hosts: all
  become: no
  user: root
  tasks:  
    - name: Find trace.log files
      find:
        paths: "{{ logs_dir }}"
        patterns: "trace.log" 
        size: 100m
        recurse: yes
      register: log_files
    - debug:
        msg: "{{ [item.path] }} "
      with_items: "{{ log_files.files }}"
