- name: find and delete trace.log
  hosts: all
  become: no
  user: root
  tasks:  
    - name: Find trace.log files
      ansible.builtin.find:
        paths: "{{ logs_dir }}"
        patterns: "trace.log" 
        size: 100m
        recurse: yes
      register: log_files
      
    - name: Delete trace.log files
      file:
        path: "{{ item.path }}"
        state: absent
      with_items: "{{ log_files.files }}"
