- name: Create a directory for ssl cert
  hosts: localhost
  become: false
  tasks:
    - name: Create a directory
      ansible.builtin.file:
        path: /tmp/zalupa
        state: directory
        mode: 0775

- name: Update Let's Encrypt Certificate
  hosts: source
  become: false
  user: root
  tasks:
    - name: up ens224 
      shell: "ifup ens224" 
      ignore_errors: yes
      changed_when: true
      failed_when: false

    - name: pause for "{{ wait_seconds | int }}" second(s)
      ansible.builtin.pause:
        seconds: "{{ wait_seconds | int }}"

    - name: Renew Let's Encrypt certificate
      shell: "certbot renew --cert-name {{ cert_name }}"
      args:
        warn: true 

    - name: pause for {{ wait_seconds | int }} second(s)
      ansible.builtin.pause:
        seconds: "{{ wait_seconds | int }}"

    - name: down ens224 
      shell: "ifdown ens224" 
      ignore_errors: yes
      changed_when: true
      failed_when: false

    - name: Reload Caddy configuration
      systemd:
        name: caddy
        state: restarted
        daemon_reload: true

    - name: Reload Asterisk
      shell: "asterisk -rx 'module reload http'" 
      ignore_errors: yes
      changed_when: true
      failed_when: false

- hosts: source
  gather_facts: no
  tasks:
    - name: Synchronization using rsync protocol (pull)
      ansible.posix.synchronize:
        mode: pull
        src: /etc/letsencrypt/live/{{ cert_name }}/
        dest: /tmp/zalupa/
        rsync_opts:
          - "--copy-links"
          - "--delete-after"
          - "--chmod=Du=rwx,Dg=rwx,Do=rwx,Fu=rwx,Fg=rwx,Fo=rwx"
          - "-zrpth"

- hosts: queue1
  gather_facts: no
  tasks:
    - name: Synchronization using rsync protocol (pull)
      ansible.posix.synchronize:
        mode: push
        src: /tmp/zalupa/
        dest: /etc/letsencrypt/live/{{ cert_name }}/

    - name: Reload Asterisk
      shell: "asterisk -rx 'module reload http'" 
      ignore_errors: yes
      changed_when: true
      failed_when: false

- hosts: queue2
  gather_facts: no
  tasks:
    - name: Synchronization using rsync protocol (pull)
      ansible.posix.synchronize:
        mode: push
        src: /tmp/zalupa/
        dest: /etc/letsencrypt/live/{{ cert_name }}/

    - name: Reload Asterisk
      shell: "asterisk -rx 'module reload http'" 
      ignore_errors: yes
      changed_when: true
      failed_when: false

- hosts: queue3
  gather_facts: no
  tasks:
    - name: Synchronization using rsync protocol (pull)
      ansible.posix.synchronize:
        mode: push
        src: /tmp/zalupa/
        dest: /etc/letsencrypt/live/{{ cert_name }}/

    - name: Reload Asterisk
      shell: "asterisk -rx 'module reload http'" 
      ignore_errors: yes
      changed_when: true
      failed_when: false

- hosts: queue4
  gather_facts: no
  tasks:
    - name: Synchronization using rsync protocol (pull)
      ansible.posix.synchronize:
        mode: push
        src: /tmp/zalupa/
        dest: /etc/letsencrypt/live/{{ cert_name }}/

    - name: Reload Asterisk
      shell: "asterisk -rx 'module reload http'" 
      ignore_errors: yes
      changed_when: true
      failed_when: false

- hosts: localhost
  tasks:
    - name: Remove /tmp/zalupa directory
      ansible.builtin.file:
        state: absent
        path: /tmp/zalupa/
