- name: Change root password 
  hosts: all
  become: false
  user: root
  gather_facts: false
  vars_prompt:
    - name: new_root_password_encrypted
      prompt: Please enter the new root password
      private: true
      encrypt: sha512_crypt
      confirm: true
      unsafe: true
  tasks:
    - name: Change root password
      user:
        name: root
        password: "{{ new_root_password_encrypted }}"
